In [18]:
import pandas as pd
import numpy as np
from datasets import load_dataset
import openai
from openai import OpenAI
import time
import copy
from tqdm import tqdm

import importlib
import sys; sys.path.append("../src")
import supernova
importlib.reload(supernova)
ROOT_DIR = '..'

from supernova import (
    SupernovaExample,
    get_llm_generated_answer,
    get_llm_output,
    query_openai,
    parse_measurement_string,
    format_time_series_for_prompt,
    isolate_individual_features,
    distill_relevant_features,
    calculate_expert_alignment_score,
    calculate_expert_alignment_scores_old,
    calculate_expert_alignment_score_for_category,
    get_claims_by_category,
    group_claims_by_category,
    make_alignment_matrix,
)

In [2]:
# 0 microlens-single (mu-Lens-Single)
# 1 tidal disruption event (TDE)
# 2 eclipsing binary (EB)
# 3 type II supernova (SNII)
# 4 peculiar type Ia supernova (SNIax)
# 5 Mira variable
# 6 type Ibc supernova (SNIbc)
# 7 kilonova (KN)
# 8 M-dwarf
# 9 peculiar type Ia supernova (SNIa-91bg)
# 10 active galactic nuclei (AGN)
# 11 type Ia supernova (SNIa)
# 12 RR-Lyrae (RRL)
# 13 superluminous supernova (SLSN-I)

### Load Supernova Data

In [ ]:
supernova_data = load_dataset("BrachioLab/supernova")
supernova_data = supernova_data['test'].to_pandas()
supernova_data = supernova_data.sample(1, random_state=11).reset_index(drop=True)

In [14]:
supernova_examples = []
for idx, row in tqdm(supernova_data.iterrows(), total=supernova_data.shape[0], desc="Processing Rows"):
    time_series_data = row['data']
    llm_label, explanation = get_llm_generated_answer(time_series_data)
    if llm_label is None:
        continue
    supernova_examples.append(SupernovaExample(
        file=row['filename'],
        time_series_data=time_series_data,
        ground_truth=row['label'],
        llm_label=llm_label,
        llm_explanation=explanation
    ))

Processing Rows: 100% 107/107 [02:47<00:00,  1.56s/it]

In [2]:
import os
from pathlib import Path
import pandas as pd
from PIL import Image
try:
    from tqdm.notebook import tqdm
except ImportError:
    from tqdm import tqdm

In [3]:
data_dir = Path('/shared_data0/chaenyk/supernova/tfix-examples')

# Target image size (width, height)
target_size = (256, 125)

# Define the number of classes and images per class
num_classes = 14
num_images_per_class = 1

In [4]:
from pathlib import Path
from PIL import Image
import pandas as pd
import os
from tqdm import tqdm
image_object_list = [] # Store PIL Image objects
label_list = []
file_name_list = [] # <--- ADDED: List to store file names

print(f"Starting image processing from: {data_dir}")
print(f"Target resize dimensions (width, height): {target_size}")

# --- Optional: Add directory check from previous step to ensure path is correct ---
print(f"\n--- Checking contents of: {data_dir} ---")
try:
    if data_dir.exists():
        print("Directory exists.")
        contents = os.listdir(data_dir)
        if not contents:
            print("Directory is EMPTY.")
        else:
            # Limit output if directory is large
            print(f"First few items found: {contents[:10]}...")
    else:
        print(f"!!! Directory DOES NOT EXIST: {data_dir} !!!") # Enhanced message
except Exception as e:
    print(f"Error accessing directory {data_dir}: {e}")
print("--- End check ---")
# --- End directory check ---


# Iterate through all potential files
for i in tqdm(range(num_classes), desc="Processing Classes"):
    for j in range(num_images_per_class):
        file_name = f"supernova_{i}_{j}.png" # This is the file name
        file_path = data_dir / file_name

        try:
            # Check if the file actually exists
            if file_path.is_file():
                # Open the image using Pillow
                # Keep the file handle open only as long as needed
                with Image.open(file_path) as img:
                    # Resize the image
                    img_resized = img.resize(target_size)

                    # Store PIL object directly
                    image_object_list.append(img_resized.copy())
                    label_list.append(i) # Append the label (class index i)
                    file_name_list.append(file_name) # <--- ADDED: Append the file name

            # else:
                # Optional: Print a warning if a file is expected but not found
                # print(f"Warning: File not found - {file_path}")
                # pass # Silently skip missing files

        except FileNotFoundError:
            # Should be caught by is_file(), but good practice to keep
            print(f"Error: File not found {file_path}")
        except Exception as e:
            print(f"Error processing file {file_path}: {e}")
            # Decide how to handle errors: skip the file, stop the script, etc.

# Create the Pandas DataFrame
print("\nCreating DataFrame...")
df = pd.DataFrame({
    'label': label_list,
    'data': image_object_list,
    'filename': file_name_list # <--- ADDED: Include file_name_list in DataFrame
})

# --- Verification ---
print("\nDataFrame created successfully!")
print(f"Number of entries in DataFrame: {len(df)}")
print("\nDataFrame Info:")
# The 'data' column (containing PIL Image objects) will have dtype 'object'
# The 'file_name' column will also have dtype 'object' (strings)
df.info()

print("\nDataFrame Head:")
print(df.head())

# Optional: Check if the number of entries matches expectations
expected_files = len(image_object_list)
if expected_files > 0:
    print(f"\nSuccessfully processed {expected_files} images.")
    if len(label_list) == expected_files and len(file_name_list) == expected_files:
        print("All lists are of the same length, DataFrame should be consistent.")
    else:
        print("Warning: List lengths mismatch, check processing logic.")
else:
    print("\nNo images were processed. Please check 'data_dir' and file naming convention.")

Starting image processing from: /shared_data0/chaenyk/supernova/tfix-examples
Target resize dimensions (width, height): (256, 125)

--- Checking contents of: /shared_data0/chaenyk/supernova/tfix-examples ---
Directory exists.
First few items found: ['supernova_10_7.png', 'supernova_4_1.png', 'supernova_10_0.png', 'supernova_4_6.png', 'supernova_8_6.png', 'supernova_3_2.png', 'supernova_8_1.png', 'supernova_3_5.png', 'supernova_1_3.png', 'supernova_1_4.png']...
--- End check ---

Processing Classes: 100% 14/14 [00:00<00:00, 24.10it/s]

Creating DataFrame...

DataFrame created successfully!
Number of entries in DataFrame: 14

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   label     14 non-null     int64
 1   data      14 non-null     object
 2   filename  14 non-null     object
dtypes: int64(1), object(2)
memory usage: 464.0+ bytes

DataFrame Head:
   label                                               data           filename
0      0  <PIL.Image.Image image mode=RGBA size=256x125 ...  supernova_0_0.png
1      1  <PIL.Image.Image image mode=RGBA size=256x125 ...  supernova_1_0.png
2      2  <PIL.Image.Image image mode=RGBA size=256x125 ...  supernova_2_0.png
3      3  <PIL.Image.Image image mode=RGBA size=256x125 ...  supernova_3_0.png
4      4  <PIL.Image.Image image mode=RGBA size=256x125 ...  supernova_4_0.png

Successfully processed 14 images.
All lists are of the same length, DataFrame should be consistent.

In [5]:
supernova_data = df
supernova_data

,label,data,filename
0,0,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_0_0.png
1,1,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_1_0.png
2,2,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_2_0.png
3,3,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_3_0.png
4,4,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_4_0.png
5,5,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_5_0.png
6,6,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_6_0.png
7,7,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_7_0.png
8,8,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_8_0.png
9,9,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_9_0.png
10,10,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_10_0.png
11,11,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_11_0.png
12,12,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_12_0.png
13,13,<PIL.Image.Image image mode=RGBA size=256x125 ...,supernova_13_0.png

In [7]:
supernova_data = supernova_data.iloc[[0]].copy()
supernova_data

   label                                               data           filename
0      0  <PIL.Image.Image image mode=RGBA size=256x125 ...  supernova_0_0.png

In [8]:
supernova_examples = []
for idx, row in tqdm(supernova_data.iterrows(), total=supernova_data.shape[0], desc="Processing Rows"):
    time_series_data = row['data']
    llm_label, explanation = get_llm_generated_answer(time_series_data)
    if llm_label is None:
        continue
    supernova_examples.append(SupernovaExample(
        file=row['filename'],
        time_series_data=time_series_data,
        ground_truth=row['label'],
        llm_label=llm_label,
        llm_explanation=explanation
    ))

Processing Rows: 100% 1/1 [00:00<00:00, 22.52it/s]

In [9]:
supernova_examples[0].llm_explanation

'The time series shows periodic dips in flux, which are characteristic of an eclipsing binary system. These dips occur when one star passes in front of the other, causing a temporary decrease in brightness. The presence of multiple wavelengths with synchronized dips supports the classification as an EB.'

In [10]:
supernova_examples = supernova_examples[:1]

### Stage 1: Atomic claim extraction

In [11]:
for example in supernova_examples:
    claims = isolate_individual_features(example.llm_explanation)
    if claims is None:
        continue
    example.claims = [claim.strip() for claim in claims]

In [12]:
supernova_examples[0].claims

['The time series shows periodic dips in flux.',
 'The dips are characteristic of an eclipsing binary system.',
 'The dips occur when one star passes in front of the other.',
 'The brightness decreases temporarily due to the occultation by the other star.',
 'The dips are observed across multiple wavelengths.',
 'The dips are synchronized across multiple wavelengths.',
 'The synchronized, multi-wavelength dips support the classification as an EB.']

### Stage 2: Distill relevant claims

In [13]:
for example in supernova_examples:
    relevant_claims = distill_relevant_features(example.time_series_data, example.llm_label, example.claims)
    example.relevant_claims = relevant_claims

In [14]:
supernova_examples[0].relevant_claims

['The time series shows periodic dips in flux.',
 'The dips are characteristic of an eclipsing binary system.',
 'The dips occur when one star passes in front of the other.',
 'The brightness decreases temporarily due to the occultation by the other star.',
 'The dips are observed across multiple wavelengths.',
 'The dips are synchronized across multiple wavelengths.',
 'The synchronized, multi-wavelength dips support the classification as an EB.']

### Stage 3: Calculate alignment scores

In [19]:
# for model in models:
model = 'gpt-5-nano'
print(f"=== Using model {model} ===")
# for method in methods:
method = 'vanilla'
print(f"=== Using method {method} ===")
eval_model = 'gpt-5-nano'

load_path = os.path.join(ROOT_DIR, f'results/{method}/supernova_{model}.json')
save_path = os.path.join(ROOT_DIR, f'results/{method}/supernova_{model}_v2_{eval_model}.json')

#with open(load_path) as input_file:
#    results = json.load(input_file)

new_results = []
results = supernova_examples
num_examples = len(results)
for di in tqdm(range(num_examples)):
    result = results[di]
    relevant_claims = result.relevant_claims

    claims_by_category, category_alignment_scores, category_alignment_reasonings = calculate_expert_alignment_score(
        relevant_claims, 
        eval_model,
        verbose=True
    )
    
    new_result = copy.deepcopy(result)
    alignment_matrix = make_alignment_matrix(
        result.claims,
        claims_by_category,
        category_alignment_scores
    )
    new_results.append(new_result)
    
    break

=== Using model gpt-5-nano ===
=== Using method vanilla ===

  0% 0/1 [00:00<?, ?it/s]

===============================================
GETTING CLAIMS BY CATEGORY
category:  Contiguous non-zero flux
claims:  ['The time series shows periodic dips in flux.', 'The dips are characteristic of an eclipsing binary system.', 'The dips occur when one star passes in front of the other.', 'The brightness decreases temporarily due to the occultation by the other star.', 'The dips are observed across multiple wavelengths.', 'The dips are synchronized across multiple wavelengths.', 'The synchronized, multi-wavelength dips support the classification as an EB.']
response: RELATED CLAIMS:
The time series shows periodic dips in flux.
The dips are characteristic of an eclipsing binary system.
The dips occur when one star passes in front of the other.
The brightness decreases temporarily due to the occultation by the other star.
The dips are observed across multiple wavelengths.
The dips are synchronized across multiple wavelengths.
The synchronized, multi-wavelength dips support the classification as an EB.
REASONING:
These claims directly describe flux-based variability consistent with an eclipsing binary (EB): periodic dips define time windows of reduced flux due to occultation, and the explicit mechanism (one star passing in front of the other) ties the dips to EB physics. Multi-wavelength observations and synchronization further support a coherent, astrophysical dip signal rather than noise. All listed claims pertain to EB-related flux dips; none are about unrelated categories, so no claims were excluded.
===============================================
category:  Contiguous non-zero flux
related_claims:  ['The time series shows periodic dips in flux.', 'The dips are characteristic of an eclipsing binary system.', 'The dips occur when one star passes in front of the other.', 'The brightness decreases temporarily due to the occultation by the other star.', 'The dips are observed across multiple wavelengths.', 'The dips are synchronized across multiple wavelengths.', 'The synchronized, multi-wavelength dips support the classification as an EB.']
reasoning:  These claims directly describe flux-based variability consistent with an eclipsing binary (EB): periodic dips define time windows of reduced flux due to occultation, and the explicit mechanism (one star passing in front of the other) ties the dips to EB physics. Multi-wavelength observations and synchronization further support a coherent, astrophysical dip signal rather than noise. All listed claims pertain to EB-related flux dips; none are about unrelated categories, so no claims were excluded.
===============================================
GETTING CLAIMS BY CATEGORY
category:  Rise–decline rates
claims:  ['The time series shows periodic dips in flux.', 'The dips are characteristic of an eclipsing binary system.', 'The dips occur when one star passes in front of the other.', 'The brightness decreases temporarily due to the occultation by the other star.', 'The dips are observed across multiple wavelengths.', 'The dips are synchronized across multiple wavelengths.', 'The synchronized, multi-wavelength dips support the classification as an EB.']
response: RELATED CLAIMS:
N/A
REASONING:
The category targets rise–decline rates characteristic of supernova light curves (fast rise, slow fade). The provided claims describe eclipsing binary (EB) light-curve dips caused by occultation, including periodic dips and multi-wavelength synchronization, which pertain to EB classification rather than SN rise–decline morphologies. None of the claims address SN rise–decline behavior, so no claims are related. The EB-specific claims are excluded as they pertain to a different astrophysical scenario.
===============================================
category:  Rise–decline rates
related_claims:  []
reasoning:  The category targets rise–decline rates characteristic of supernova light curves (fast rise, slow fade). The provided claims describe eclipsing binary (EB) light-curve dips caused by occultation, including periodic dips and multi-wavelength synchronization, which pertain to EB classification rather than SN rise–decline morphologies. None of the claims address SN rise–decline behavior, so no claims are related. The EB-specific claims are excluded as they pertain to a different astrophysical scenario.
===============================================
GETTING CLAIMS BY CATEGORY
category:  Photometric amplitude
claims:  ['The time series shows periodic dips in flux.', 'The dips are characteristic of an eclipsing binary system.', 'The dips occur when one star passes in front of the other.', 'The brightness decreases temporarily due to the occultation by the other star.', 'The dips are observed across multiple wavelengths.', 'The dips are synchronized across multiple wavelengths.', 'The synchronized, multi-wavelength dips support the classification as an EB.']
response: RELATED CLAIMS:
- The time series shows periodic dips in flux.
- The dips are characteristic of an eclipsing binary system.
- The dips occur when one star passes in front of the other.
- The brightness decreases temporarily due to the occultation by the other star.
- The dips are observed across multiple wavelengths.
- The dips are synchronized across multiple wavelengths.
- The synchronized, multi-wavelength dips support the classification as an EB.
REASONING:
(1) These claims are directly about eclipsing binaries (EBs): periodic dips in brightness caused by one star occulting the other, which aligns with low-amplitude, periodic variability rather than high-amplitude explosive events. They provide atomic, evidence-level support for identifying an EB, including the cause (occultation), timing (periodicity), and observational consistency across wavelengths.
(2) No claims here describe high-energy explosive transients; all statements pertain to EB photometric behavior, so there are no non-selected claims of a different category to exclude beyond recognizing the EB-focused scope.
===============================================
category:  Photometric amplitude
related_claims:  ['- The time series shows periodic dips in flux.', '- The dips are characteristic of an eclipsing binary system.', '- The dips occur when one star passes in front of the other.', '- The brightness decreases temporarily due to the occultation by the other star.', '- The dips are observed across multiple wavelengths.', '- The dips are synchronized across multiple wavelengths.', '- The synchronized, multi-wavelength dips support the classification as an EB.']
reasoning:  (1) These claims are directly about eclipsing binaries (EBs): periodic dips in brightness caused by one star occulting the other, which aligns with low-amplitude, periodic variability rather than high-amplitude explosive events. They provide atomic, evidence-level support for identifying an EB, including the cause (occultation), timing (periodicity), and observational consistency across wavelengths.
(2) No claims here describe high-energy explosive transients; all statements pertain to EB photometric behavior, so there are no non-selected claims of a different category to exclude beyond recognizing the EB-focused scope.
===============================================
GETTING CLAIMS BY CATEGORY
category:  Event duration
claims:  ['The time series shows periodic dips in flux.', 'The dips are characteristic of an eclipsing binary system.', 'The dips occur when one star passes in front of the other.', 'The brightness decreases temporarily due to the occultation by the other star.', 'The dips are observed across multiple wavelengths.', 'The dips are synchronized across multiple wavelengths.', 'The synchronized, multi-wavelength dips support the classification as an EB.']
response: RELATED CLAIMS:
N/A
REASONING:
- The category focuses on event duration from first detection to return to baseline to distinguish long-lived transients (e.g., kilonovae, SLSN) from longer-term variability (e.g., AGN). None of the provided claims quantify or explicitly reference the total event duration.
- The claims pertain to eclipsing-binary (EB) characteristics (periodic dips, cause of dips, multi-wavelength behavior) rather than to the overall temporal duration of the event, so they do not serve as atomic evidence for the event-duration criterion. The only timing-related claim (“The time series shows periodic dips in flux”) implies periodicity but does not specify duration to baseline, and thus is not a direct match for the category’s duration criterion.
===============================================
category:  Event duration
related_claims:  []
reasoning:  - The category focuses on event duration from first detection to return to baseline to distinguish long-lived transients (e.g., kilonovae, SLSN) from longer-term variability (e.g., AGN). None of the provided claims quantify or explicitly reference the total event duration.
- The claims pertain to eclipsing-binary (EB) characteristics (periodic dips, cause of dips, multi-wavelength behavior) rather than to the overall temporal duration of the event, so they do not serve as atomic evidence for the event-duration criterion. The only timing-related claim (“The time series shows periodic dips in flux”) implies periodicity but does not specify duration to baseline, and thus is not a direct match for the category’s duration criterion.
===============================================
GETTING CLAIMS BY CATEGORY
category:  Periodic light curves
claims:  ['The time series shows periodic dips in flux.', 'The dips are characteristic of an eclipsing binary system.', 'The dips occur when one star passes in front of the other.', 'The brightness decreases temporarily due to the occultation by the other star.', 'The dips are observed across multiple wavelengths.', 'The dips are synchronized across multiple wavelengths.', 'The synchronized, multi-wavelength dips support the classification as an EB.']
response: RELATED CLAIMS:
The time series shows periodic dips in flux.
The dips are characteristic of an eclipsing binary system.
The dips occur when one star passes in front of the other.
The brightness decreases temporarily due to the occultation by the other star.
The dips are observed across multiple wavelengths.
The dips are synchronized across multiple wavelengths.
The synchronized, multi-wavelength dips support the classification as an EB.
REASONING:
All seven claims directly describe features of periodic eclipsing events (periodic dips, eclipse geometry, and multi-wavelength consistency) that are diagnostic of eclipsing binaries and periodic light curves. They collectively support the category’s emphasis on stable periods and EB-like light-curve morphology. No claims were found that pertain to unrelated classes or non-periodic transients, so none are excluded.
===============================================
category:  Periodic light curves
related_claims:  ['The time series shows periodic dips in flux.', 'The dips are characteristic of an eclipsing binary system.', 'The dips occur when one star passes in front of the other.', 'The brightness decreases temporarily due to the occultation by the other star.', 'The dips are observed across multiple wavelengths.', 'The dips are synchronized across multiple wavelengths.', 'The synchronized, multi-wavelength dips support the classification as an EB.']
reasoning:  All seven claims directly describe features of periodic eclipsing events (periodic dips, eclipse geometry, and multi-wavelength consistency) that are diagnostic of eclipsing binaries and periodic light curves. They collectively support the category’s emphasis on stable periods and EB-like light-curve morphology. No claims were found that pertain to unrelated classes or non-periodic transients, so none are excluded.
===============================================
GETTING CLAIMS BY CATEGORY
category:  Secondary maxima
claims:  ['The time series shows periodic dips in flux.', 'The dips are characteristic of an eclipsing binary system.', 'The dips occur when one star passes in front of the other.', 'The brightness decreases temporarily due to the occultation by the other star.', 'The dips are observed across multiple wavelengths.', 'The dips are synchronized across multiple wavelengths.', 'The synchronized, multi-wavelength dips support the classification as an EB.']
response: RELATED CLAIMS:
N/A
REASONING:
The category targets secondary maxima (or shoulders) in red/near-IR bands that are characteristic of Type Ia supernovae and are not common in core-collapse SNe. None of the provided claims mention SN Ia secondary maxima, their presence/absence in SN samples, or related SN morphology. The claims instead describe eclipsing-binary–related dips and multi-wavelength synchronization, which pertain to EB classification, not SN Ia secondary-maximum features. Therefore no claims are directly related to the category.
===============================================
category:  Secondary maxima
related_claims:  []
reasoning:  The category targets secondary maxima (or shoulders) in red/near-IR bands that are characteristic of Type Ia supernovae and are not common in core-collapse SNe. None of the provided claims mention SN Ia secondary maxima, their presence/absence in SN samples, or related SN morphology. The claims instead describe eclipsing-binary–related dips and multi-wavelength synchronization, which pertain to EB classification, not SN Ia secondary-maximum features. Therefore no claims are directly related to the category.
===============================================
GETTING CLAIMS BY CATEGORY
category:  Monotonic flux trends
claims:  ['The time series shows periodic dips in flux.', 'The dips are characteristic of an eclipsing binary system.', 'The dips occur when one star passes in front of the other.', 'The brightness decreases temporarily due to the occultation by the other star.', 'The dips are observed across multiple wavelengths.', 'The dips are synchronized across multiple wavelengths.', 'The synchronized, multi-wavelength dips support the classification as an EB.']
response: RELATED CLAIMS:
N/A
REASONING:
No claims describe monotonic flux trends (plateaus or linear decays) relevant to distinguishing SN II-P/II-L. All provided claims pertain to eclipsing binary (EB) dips and EB-related features, which do not support the category of monotonic flux evolution. The EB-specific claims are excluded because they describe non-monotonic, occultation-driven flux variations rather than smooth, monotonic evolution.
===============================================
category:  Monotonic flux trends
related_claims:  []
reasoning:  No claims describe monotonic flux trends (plateaus or linear decays) relevant to distinguishing SN II-P/II-L. All provided claims pertain to eclipsing binary (EB) dips and EB-related features, which do not support the category of monotonic flux evolution. The EB-specific claims are excluded because they describe non-monotonic, occultation-driven flux variations rather than smooth, monotonic evolution.
===============================================
expert alignment score for category:  Contiguous non-zero flux
response:  Reasoning: The claims describe periodic flux dips due to an eclipsing binary, indicating genuine astrophysical variability and multi-wavelength coherence, which aligns with the idea of identifying real transient flux changes. However, they do not explicitly reference contiguous non-zero flux segments or using such segments to define specific time windows for extracting transient features, which is the core focus of the category. Therefore, the alignment is partial.
Category Alignment Rating: partial
===============================================
expert alignment score for category:  Rise–decline rates
response:  Reasoning: There are no claims provided to evaluate against the rise–decline rates category, so no alignment can be assessed.
Category Alignment Rating: none

  0% 0/1 [00:00<?, ?it/s]

===============================================
expert alignment score for category:  Photometric amplitude
response:  Reasoning: The claims describe periodic flux dips due to eclipses in an eclipsing binary, which fits the idea of a low-amplitude periodic variable and notes multi-wavelength synchronization. However, they do not explicitly reference the amplitude magnitude (peak-to-trough) or explicitly contrast these low-amplitude variations with high-energy explosive events, which is the central discriminant of the category. Therefore, the alignment is partial.
Category Alignment Rating: partial
===============================================
expert alignment score for category:  Event duration
response:  Reasoning: There are no claims provided, so there is nothing to assess against the 'Event duration' category; therefore alignment is none.
Category Alignment Rating: none
===============================================
expert alignment score for category:  Periodic light curves
response:  Reasoning: The claims correctly identify periodic eclipsing features, the eclipse geometry, and multi-wavelength consistency, which align with the idea of periodic EB signals. However, they do not explicitly mention the stability of the period or the use of distinctive Fourier amplitude/phase ratios (e.g., φ21, φ31) that the category emphasizes. Therefore, the alignment is partial.
Category Alignment Rating: partial
===============================================
expert alignment score for category:  Secondary maxima
response:  Reasoning: No claims are given, so there is nothing to align with the category describing secondary maxima features characteristic of SNe Ia.
Category Alignment Rating: none
===============================================
expert alignment score for category:  Monotonic flux trends
response:  Reasoning: There are no claims provided (N/A), so there is no information to assess alignment with the monotonic flux trends category.
Category Alignment Rating: none

In [20]:
claims_by_category

{'Contiguous non-zero flux': ['The time series shows periodic dips in flux.',
  'The dips are characteristic of an eclipsing binary system.',
  'The dips occur when one star passes in front of the other.',
  'The brightness decreases temporarily due to the occultation by the other star.',
  'The dips are observed across multiple wavelengths.',
  'The dips are synchronized across multiple wavelengths.',
  'The synchronized, multi-wavelength dips support the classification as an EB.'],
 'Rise–decline rates': [],
 'Photometric amplitude': ['- The time series shows periodic dips in flux.',
  '- The dips are characteristic of an eclipsing binary system.',
  '- The dips occur when one star passes in front of the other.',
  '- The brightness decreases temporarily due to the occultation by the other star.',
  '- The dips are observed across multiple wavelengths.',
  '- The dips are synchronized across multiple wavelengths.',
  '- The synchronized, multi-wavelength dips support the classification as an EB.'],
 'Event duration': [],
 'Periodic light curves': ['The time series shows periodic dips in flux.',
  'The dips are characteristic of an eclipsing binary system.',
  'The dips occur when one star passes in front of the other.',
  'The brightness decreases temporarily due to the occultation by the other star.',
  'The dips are observed across multiple wavelengths.',
  'The dips are synchronized across multiple wavelengths.',
  'The synchronized, multi-wavelength dips support the classification as an EB.'],
 'Secondary maxima': [],
 'Monotonic flux trends': []}

In [21]:
category_alignment_scores

{'Contiguous non-zero flux': 0.5,
 'Rise–decline rates': 0.0,
 'Photometric amplitude': 0.5,
 'Event duration': 0.0,
 'Periodic light curves': 0.5,
 'Secondary maxima': 0.0,
 'Monotonic flux trends': 0.0}

In [22]:
category_alignment_reasonings

{'Contiguous non-zero flux': 'The claims describe periodic flux dips due to an eclipsing binary, indicating genuine astrophysical variability and multi-wavelength coherence, which aligns with the idea of identifying real transient flux changes. However, they do not explicitly reference contiguous non-zero flux segments or using such segments to define specific time windows for extracting transient features, which is the core focus of the category. Therefore, the alignment is partial.',
 'Rise–decline rates': 'There are no claims provided to evaluate against the rise–decline rates category, so no alignment can be assessed.',
 'Photometric amplitude': 'The claims describe periodic flux dips due to eclipses in an eclipsing binary, which fits the idea of a low-amplitude periodic variable and notes multi-wavelength synchronization. However, they do not explicitly reference the amplitude magnitude (peak-to-trough) or explicitly contrast these low-amplitude variations with high-energy explosive events, which is the central discriminant of the category. Therefore, the alignment is partial.',
 'Event duration': "There are no claims provided, so there is nothing to assess against the 'Event duration' category; therefore alignment is none.",
 'Periodic light curves': 'The claims correctly identify periodic eclipsing features, the eclipse geometry, and multi-wavelength consistency, which align with the idea of periodic EB signals. However, they do not explicitly mention the stability of the period or the use of distinctive Fourier amplitude/phase ratios (e.g., φ21, φ31) that the category emphasizes. Therefore, the alignment is partial.',
 'Secondary maxima': 'No claims are given, so there is nothing to align with the category describing secondary maxima features characteristic of SNe Ia.',
 'Monotonic flux trends': 'There are no claims provided (N/A), so there is no information to assess alignment with the monotonic flux trends category.'}

In [23]:
alignment_matrix

array([[0.5, 0. , 0. , 0. , 0.5, 0. , 0. ],
       [0.5, 0. , 0. , 0. , 0.5, 0. , 0. ],
       [0.5, 0. , 0. , 0. , 0.5, 0. , 0. ],
       [0.5, 0. , 0. , 0. , 0.5, 0. , 0. ],
       [0.5, 0. , 0. , 0. , 0.5, 0. , 0. ],
       [0.5, 0. , 0. , 0. , 0.5, 0. , 0. ],
       [0.5, 0. , 0. , 0. , 0.5, 0. , 0. ]])

In [24]:
alignment_matrix.max(axis=-1), alignment_matrix.max(axis=-1).mean()

(array([0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5]), 0.5)